feat: small updates for steps tracing
paradigmxyz/revm-inspectors pull request #152
Opened 2024-06-24 20:12 UTC by klkvr

- Adds `record_returndata_snapshots` flag to config which enables snapshots of `interp.return_data_buffer`
- Adds `record_opcodes_filter` parameter which allows to only record specific opcodes.
- Adds `gas_used` field for `CallTraceStep`

This should be enough to migrate foundry's debugger to using `TracingInspector` from here, I will open PR for this later today.

2024-06-24 20:17 UTC, DaniPopes requested changes

2024-06-24 20:17 UTC, DaniPopes commented on src/tracing/config.rs
> +pub struct OpcodeFilter([bool; 256]);
This is 256 bytes not bits, use `U256` to make it bits

2024-06-24 20:17 UTC, DaniPopes commented on src/tracing/config.rs
> +    pub fn enabled(&self, op: &OpCode) -> bool {
```suggestion
    pub fn is_enabled(&self, op: OpCode) -> bool {
```

2024-06-24 20:44 UTC, klkvr commented
this conflicts with approved https://github.com/paradigmxyz/revm-inspectors/pull/84 as it relies on previous recorded step always containing memory during previous instruction. This is wouldn't be true if `record_opcodes_filter` is configured

2024-06-25 05:50 UTC, DaniPopes commented
We could just override the filter to say that we're tracing memory opcodes if we also want memory in that case

2024-06-25 15:29 UTC, mattsse commented
> We could just override the filter to say that we're tracing memory opcodes if we also want memory in that case

that makes sense

2024-06-25 17:38 UTC, klkvr commented
> We could just override the filter to say that we're tracing memory opcodes if we also want memory in that case

hmm, perhaps we should just fallback to old behavior in that case? if user provided filter to only collect `JUMP`s for example it might be unexpected that we'd collect 11 other opcodes as well potentially increasing memory usage

2024-06-25 18:40 UTC, mattsse requested changes
if I'm reading this correctly, then this does not change the existing recording logic and only adds returndata recording based on opcode filter?

the overhead is negligible here

we can do @DaniPopes suggestion separately I believe

2024-06-25 18:40 UTC, mattsse commented on src/tracing/mod.rs
> +        let record = self.config.record_opcodes_filter.as_ref().map_or(true, |f| f.is_enabled(&op));
could we make this a function instead?

2024-06-25 18:40 UTC, mattsse commented on src/tracing/mod.rs
> +    record: bool,
needs docs what for what this tracks

2024-06-25 18:40 UTC, mattsse commented on src/tracing/types.rs
> +    pub returndata: Bytes,
I do remember we had this at some point

2024-06-25 18:53 UTC, mattsse approved these changes
lgtm, pending @DaniPopes

2024-06-25 18:53 UTC, klkvr commented
> if I'm reading this correctly, then this does not change the existing recording logic and only adds returndata recording based on opcode filter?

opcode filter and returndata are separate configs

returndata is recorded in the same way as memory: if `record_returndata_snapshots` is true, we always save snapshot

and opcode filter is just a way to make tracer record only specific steps to optimize memory usage if we're only interested in a small subset of steps. e.g. this is the case for internal fns tracking in foundry where we only want `JUMP`s and `JUMPDEST`s along with their stack and memory snapshots

2024-06-25 19:08 UTC, DaniPopes approved these changes

2024-06-25 19:26 UTC, merged