feat: add immediate bytes recording
paradigmxyz/revm-inspectors pull request #169
Opened 2024-07-17 23:38 UTC by klkvr

before EOF those were only present for `PUSH*` opcodes, and they were trivial to obtain by looking at the top of the stack, now it is a bit more complex, so this would be useful

2024-07-18 02:53 UTC, DaniPopes requested changes

2024-07-18 02:53 UTC, DaniPopes commented on src/tracing/mod.rs
> +                    .get(pc + 1..pc + 1 + op.info().immediate_size() as usize)
note that this doesn't include the full `RJUMPV` immediate, which is calculated as `len = (imm[0] + 1) * 2`

2024-07-18 02:53 UTC, DaniPopes commented on src/tracing/mod.rs
> +                    .get(pc + 1..pc + 1 + op.info().immediate_size() as usize)
We can `slice` here to avoid allocating for each immediate

2024-07-18 10:42 UTC, DaniPopes approved these changes

2024-07-19 09:08 UTC, mattsse approved these changes

2024-07-19 09:08 UTC, merged