Use borrowed Arena in GethTraceBuilder
paradigmxyz/revm-inspectors pull request #178
Opened 2024-08-10 07:04 UTC by nkysg

Closes https://github.com/paradigmxyz/revm-inspectors/issues/65

2024-08-10 13:34 UTC, DaniPopes commented on src/tracing/builder/geth.rs
> +    nodes: Cow<'a, Vec<CallTraceNode>>,
should be [CallTraceNode]>

2024-08-10 13:51 UTC, mattsse requested changes
cool, some nits and suggestions

2024-08-10 13:51 UTC, mattsse commented on Cargo.toml
could you submit this as a separate pr?

2024-08-10 13:51 UTC, mattsse commented on src/tracing/builder/geth.rs
> +    pub fn new(
I'd like to keep this function as is and add a new one `borrowed` instead

2024-08-10 13:51 UTC, mattsse commented on src/tracing/builder/geth.rs
> +pub struct GethTraceBuilder<'a> {
This should then also implement `ToOwned`

2024-08-10 13:51 UTC, mattsse commented on src/tracing/builder/geth.rs
> +    pub fn geth_call_traces(&self, opts: &CallConfig, gas_used: u64) -> CallFrame {
this can stay `CallConfig` because this type is copy

2024-08-30 06:49 UTC, mattsse approved these changes

2024-08-30 06:51 UTC, merged