(wip)feat: support no_std
paradigmxyz/revm-inspectors pull request #250
Opened 2024-12-30 01:00 UTC by stevencartavia

should close #248

2024-12-30 09:11 UTC, mattsse requested changes
cool,
the hardest part is already done I think, now we just need to deal with some features

2024-12-30 09:11 UTC, mattsse commented on Cargo.toml
> +serde_json = { version = "1.0", optional = true }
this can use the `alloc` feature

2024-12-30 09:11 UTC, mattsse commented on Cargo.toml
> +no_std = []
here we should also propagate std to everything

2024-12-30 09:11 UTC, mattsse commented on src/lib.rs
> +pub use colorchoice::ColorChoice;
move below mods again

2024-12-30 09:11 UTC, mattsse commented on src/tracing/mux.rs
>      #[error("error deserializing config: {0}")]
I believe this type works in no-std as long as the serde-json alloc feature is enabled

2024-12-30 09:11 UTC, mattsse commented on src/tracing/writer.rs
> +use std::io::{self, Write};
here we should rather feature gate the code that depends on this I assume

2025-01-04 10:27 UTC, mattsse requested changes
few more nits

2025-01-04 10:27 UTC, mattsse commented on Cargo.toml
> +alloy-primitives = { version = "0.8", features = ["map-hashbrown"] }
map should be sufficient here

2025-01-04 10:27 UTC, mattsse commented on Cargo.toml
> +no_std = []
this isn't required because this is the same as no-default-features
```suggestion
```

2025-01-04 10:27 UTC, mattsse commented on src/lib.rs
> +#![cfg_attr(not(feature = "std"), no_std)]
move to L17

2025-01-04 23:33 UTC, DaniPopes requested changes

2025-01-04 23:33 UTC, DaniPopes commented on src/tracing/js/bindings.rs
Please leave JS unchanged, it can never support no_std

2025-01-18 09:52 UTC, mattsse approved these changes

2025-01-18 10:09 UTC, merged