optimize memory recording
paradigmxyz/revm-inspectors pull request #84
Opened 2024-04-05 18:35 UTC by h3lio5

Record memory only when necessary, i.e., the opcode modifies the memory.

2024-04-05 18:39 UTC, mattsse requested changes

2024-04-05 18:39 UTC, mattsse commented on src/opcode.rs
> +pub const fn modifies_memory(opcode: OpCode) -> bool {
we can keep this here and then remove with the next revm release if it has this function natively

2024-04-05 18:39 UTC, mattsse commented on src/tracing/mod.rs
> +            .and_then(|is_memory_modified| {
we need to record memory snapshots per step.
so what need to do here is:

1. change `RecordedMemory(Vec<u8>)` to `RecordedMemory(Bytes)`
2. if the opcode does not modify memory, get the recorded memory snapshot from the previous recorded step, if it exist, see referenced foundry code

2024-04-05 19:07 UTC, mattsse commented on src/tracing/mod.rs
> +        let prev_recorded_memory = trace.trace.steps.last().map(|step| step.memory.clone());
can we move this inside inline to L361?

2024-04-05 19:13 UTC, mattsse requested changes
okay final request, is the type changes to `Bytes` because Bytes is cheap to clone, unlike Vec<u8>

and we should add a one line comment (see foundry code) that explains why we're using the previous step's memory

2024-04-05 19:17 UTC, h3lio5 commented
if we change the type to Bytes, we may need to change some methods of `RecordedMemory` also no? Like we wouldn't need the `resize()` method.

2024-04-05 19:22 UTC, mattsse commented
hmm, good point, I need to do some digging first and find out why we're resizing or whether this is even correct...

2024-04-05 19:26 UTC, h3lio5 commented
not relevant to this issue but can you please suggest where I can learn more in-depth about call traces, revm-inspectors design and how / where is it used (applications)?

2024-04-05 19:35 UTC, mattsse commented
you can checkout the trace_ debug_ endpoints in reth:

https://github.com/paradigmxyz/reth/blob/71c404d9cb7a678d4c0f6442a9c2b8449529fe2a/crates/rpc/rpc/src/trace.rs#L41-L41

https://github.com/paradigmxyz/reth/blob/71c404d9cb7a678d4c0f6442a9c2b8449529fe2a/crates/rpc/rpc/src/debug.rs#L44-L44

2024-04-06 04:55 UTC, mattsse commented
okay @h3lio5 I did some digging and it looks like, for geth memory is recorded before the expansion which we also do

https://github.com/ethereum/go-ethereum/blob/767b00b0b514771a663f3362dd0310fc28d40c25/core/vm/interpreter.go#L262-L274

however, this means, that this is now a bit more difficult to track, because we can only reuse the previous step's memory if the previous step does not modify memory.

for the parity tracer I think we can optimize the memory delta computation separately, I believe this is currently implemented wrong:
https://github.com/paradigmxyz/evm-inspectors/blob/main/src/tracing/builder/parity.rs#L388-L388
I assume this should only track expanded memory? which we could track separately in `RecordedMemory` on step_end

2024-04-06 16:11 UTC, h3lio5 commented
@mattsse Maybe I'm missing the point here, could you please clarify why we cannot reuse the previous step's memory if it modifies memory? 

iiuc, the `memory` field in `CallTraceStep`tracks the state of memory at that step, if the previous step modified memory and the current step doesn't modify it then the state of the memory should remain unchanged no, i.e., copy prev step memory?

2024-04-07 11:59 UTC, h3lio5 commented
I think we can fetch the prev step's opcode (if it isn't the first step in the trace) using `trace.trace.steps.get(trace.trace.steps.len() - 2)`, if it does not modify memory then reuse it's memory, otherwise get the `shared_memory.context_memory()`. Do you think this approach might work? @mattsse

2024-04-08 12:09 UTC, mattsse commented
> Do you think this approach might work?

that works yes

> why we cannot reuse the previous step's memory if it modifies memory?

we need the memory when the opcode is executed, before memory expansion, when the step_start is invoked, the opcode hasn't been executed yet, so same memory as the __after__ the previous opcode. 

> edit: ah, I get it now. The previous step memory snapshot doesn't capture the expanded memory (does tracing before expansion), so we cannot reuse the prev memory?

exactly

2024-04-15 18:12 UTC, mattsse commented
haven't forgotten about this, just need to run a few more cross client tests...

2024-06-29 19:03 UTC, DaniPopes approved these changes

2024-06-29 19:32 UTC, mattsse approved these changes

2024-06-29 19:40 UTC, DaniPopes commented
Verified manually with the forge debugger, i removed the resizing because i don't think it's worth having, this will slightly modify its behavior because loads/stores won't be highlighted if they also expand memory

2024-06-29 19:41 UTC, merged